name: mychecks
version: 1.0
timeout: 5
port: 3000
targets:
  http:
    - https://google.com
  postgresql:
    - postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
  redis:
    - redis://:redis@redis:6379
